"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:accent-1)\
[\
$os\
$username\
](fg:black bg:accent-1)\
[](fg:accent-1 bg:accent-2)\
[\
$directory\
](fg:black bg:accent-2)\
[](fg:accent-2 bg:accent-3)\
[\
$git_state\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
](fg:black bg:accent-3)\
[ ](fg:accent-3)\
"""

right_format = """
[](fg:accent-3)\
[$status](inverted bg:red fg:accent-3)\
[](fg:accent-2 bg:accent-3)\
[\
$c\
$bun\
$deno\
$golang\
$java\
$nodejs\
$perl\
$php\
$python\
$rust\
](fg:black bg:accent-2)\
[](fg:accent-1 bg:accent-2)\
[\
$aws\
$azure\
$conda\
$container\
$docker_context\
$gcloud\
$package\
](fg:black bg:accent-1)\
[](inverted fg:accent-1)\
[$time](bg:grey)\
"""

add_newline = false
palette = "jazz"

[palettes.jazz]
black = "232"
white = "7"
red = "52"
green = "22"
accent-1 = "9"
accent-2 = "13"
accent-3 = "12"

[os]
disabled = false
format = "$symbol$os"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
format = "$user "

[directory]
read_only = " 󰌾"
format = "  $path"
before_repo_root_style = ""
repo_root_style = ""
repo_root_format = "  $repo_root$path[$read_only]($read_only_style) "
truncation_length = 3

[git_state]
rebase = " rebase"
merge = " merge"
revert = " revert"
cherry_pick = " cherry pick"
bisect = " bisect"
am = " am"
am_or_rebase = " am/rebase"
format = "\\($state ($progress_current/$progress_total)\\)"

[git_branch]
symbol = " "
format = " $symbol$branch(:$remote_branch) "

[git_commit]
tag_symbol = " "
only_detached = false
tag_disabled = false
format = "($tag )"

[git_status]
conflicted = "󰏐 "
ahead = " "
behind = " "
diverged = "󰿣 "
untracked = " "
stashed = " "
modified = ""  # using git metrics
staged = " "
renamed = " "
deleted = " "
typechanged = " "
format = '($ahead_behind$all_status)'

[git_metrics]
disabled = false
added_style = "bold fg:green bg:accent-3"
deleted_style = "bold fg:red bg:accent-3"
format = "([ $added ]($added_style))([ $deleted ]($deleted_style))"

[c]
symbol = " "
format = "$symbol($version) "

[bun]
symbol = " "
format = "$symbol($version) "

[deno]
symbol = " "
format = "$symbol($version) "
detect_extensions = ['js', 'mjs', 'cjs', 'ts', 'mts', 'cts']

[golang]
symbol = " "
format = "$symbol($version) "

[java]
symbol = " "
format = "$symbol($version) "

[nodejs]
symbol = " "
format = "$symbol($version) "
detect_extensions = []

[perl]
symbol = " "
format = "$symbol($version) "

[php]
symbol = " "
format = "$symbol($version) "

[python]
symbol = " "
format = "$symbol($version) "

[rust]
symbol = "󱘗 "
format = "$symbol($version) "

[aws]
symbol = "  "
format = "$symbol($version) "

[azure]
symbol = "  "
format = "$symbol($version) "

[conda]
symbol = " "
format = "$symbol($version) "

[container]
symbol = " "
format = "$symbol($version) "

[docker_context]
symbol = " "
format = "$symbol($version) "

[gcloud]
symbol = "󱇶  "
format = "$symbol($version) "

[package]
symbol = " "
format = "$symbol($version) "

[status]
disabled = false
symbol = "✖ "
recognize_signal_code = false
format = "$symbol"

[time]
disabled = false
time_format = "%R"
format = "󰥔 $time"
