# ANSI theme for zsh-syntax-highlighting to match terminal style

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[comment]='fg=8'
ZSH_HIGHLIGHT_STYLES[alias]='fg=2'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=2'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=2'
ZSH_HIGHLIGHT_STYLES[function]='fg=2'
ZSH_HIGHLIGHT_STYLES[command]='fg=2'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=2,italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=3,italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=3'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=3'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=4'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=6'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=6'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=6'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=13'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=default'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=default'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=default'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=13'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=13'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=13'
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=11'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=11'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=11'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=1'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=11'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=1'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=11'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=default'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=1'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=default'
ZSH_HIGHLIGHT_STYLES[assign]='fg=default'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=default'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=default'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=1'
ZSH_HIGHLIGHT_STYLES[path]='fg=default'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=13'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=default'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=13'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=default'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=4'
#ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=?'
#ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]='fg=?'
#ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=?'
#ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=?'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=1'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=default'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=default'
ZSH_HIGHLIGHT_STYLES[default]='fg=default'
ZSH_HIGHLIGHT_STYLES[cursor]='standout'